import sun from '../../../assets/icons/weather/conditions/sun.svg';
import nightFull from '../../../assets/icons/weather/conditions/night-full.svg';
import nightHalf from '../../../assets/icons/weather/conditions/night-half.svg';
import fewClouds from '../../../assets/icons/weather/conditions/few-clouds.svg';
import brokenClouds from '../../../assets/icons/weather/conditions/broken-clouds.svg';
import overcastClouds from '../../../assets/icons/weather/conditions/overcast-clouds.svg';
import rain from '../../../assets/icons/weather/conditions/rain.svg';
import heavyRain from '../../../assets/icons/weather/conditions/heavy-rain.svg';
import freezingRain from '../../../assets/icons/weather/conditions/freezing-rain.svg';
import showerRain from '../../../assets/icons/weather/conditions/shower-rain.svg';
import snow from '../../../assets/icons/weather/conditions/snowing.svg';
import storm from '../../../assets/icons/weather/conditions/storm.svg';

export const Sun = sun;
export const NightFull = nightFull;
export const NightHalf = nightHalf;
export const FewClouds = fewClouds;
export const BrokenClouds = brokenClouds;
export const OvercastClouds = overcastClouds;
export const Rain = rain;
export const HeavyRain = heavyRain;
export const FreezingRain = freezingRain;
export const ShowerRain = showerRain;
export const Snow = snow;
export const Storm = storm;
